version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dmx-controller
      MYSQL_USER: dmx-controller
      MYSQL_PASSWORD: 123456
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"